eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8080
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    #  routes:
     #   - id: auths
      #    uri: http://localhost:8081
       #   predicates:
        #    - Path=/api/v1/auths/**
        #- id: traitments
         # uri: http://localhost:8089
          #predicates:
           # - Path=/api/v1/traitments/**


management:
  tracing:
    sampling:
      probability: 1.0