eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8080
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auths
          uri: http://localhost:8090
          predicates:
           - Path=/api/v1/auth/**
        - id: traitments
          uri: http://localhost:8089
          predicates:
            - Path=/file/**
        - id: factures
          uri: http://localhost:8093
          predicates:
            - Path=/facture/**


management:
  tracing:
    sampling:
      probability: 1.0